name: Agentune-analyze-main

on:
  pull_request:
    branches:
      - main
    paths:
      - 'agentune_analyze/agentune/**'
      - 'agentune_analyze/tests/**'
      - 'agentune_analyze/pyproject.toml'
      - 'agentune_analyze/poetry.lock'
      - 'agentune_analyze/mypy.ini'
      - 'agentune_analyze/.ruff.toml'
  push:
    branches:
      - main
    paths:
      - 'agentune_analyze/agentune/**'
      - 'agentune_analyze/tests/**'
      - 'agentune_analyze/pyproject.toml'
      - 'agentune_analyze/poetry.lock'
      - 'agentune_analyze/mypy.ini'
      - 'agentune_analyze/.ruff.toml'

permissions:
  contents: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  python_tests:
    uses: ./.github/workflows/python-tests.yml
    with:
      src_path: "agentune_analyze"


