name: Dependency Compatability Matrix
on:
#  schedule:
#    - cron: "0 3 * * *"   # daily
  pull_request:
  workflow_dispatch:


jobs:
  test-dependency-matrix:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
        dep-mode: ["lowest", "latest"]

    name: Python ${{ matrix.python-version }} / ${{ matrix.dep-mode }} deps

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "2.0.1"
          virtualenvs-create: false
          installer-parallel: true

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install package (latest dependency versions)
        if: matrix.dep-mode == 'latest'
        run: |
          poetry install --only dev
          uv pip install --system --resolution highest --upgrade .

      - name: Install package (oldest supported dependency versions)
        if: matrix.dep-mode == 'lowest'
        run: |
          poetry install --only dev
          uv pip install --system --resolution=lowest-direct .

      - name: Run tests
        run: |
          poetry run python -m pytest