name: Dependency Compatability Matrix
on:
#  schedule:
#    - cron: "0 3 * * *"   # daily
  pull_request:
  workflow_dispatch:


jobs:
  test-dependency-matrix:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
        dep-mode: ["lowest", "latest"]

    name: Python ${{ matrix.python-version }} / ${{ matrix.dep-mode }} deps

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "2.0.1"
          virtualenvs-create: false
          installer-parallel: true

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Build wheel
        run: |
          poetry build --format wheel

      - name: Install package (latest dependency versions)
        if: matrix.dep-mode == 'latest'
        run: |
          pip install pytest \
               pytest-asyncio \
               mypy \
               ruff \
               pytest-mypy-plugins \
               pyarrow-stubs \
               matplotlib
          pip install dist/*.whl

      - name: Install package (oldest supported dependency versions)
        if: matrix.dep-mode == 'lowest'
        run: |
          uv pip install --system pytest \
                         pytest-asyncio \
                         mypy \
                         ruff \
                         pytest-mypy-plugins \
                         pyarrow-stubs \
                         matplotlib
          uv pip install --resolution=lowest-direct dist/*.whl

      - name: Run tests
        run: |
          poetry run python -m pytest