name: Agentune-simulate-main

on:
  pull_request:
    branches:
      - main
    paths:
      - 'agentune_simulate/agentune/**'
      - 'agentune_simulate/tests/**'
      - 'agentune_simulate/pyproject.toml'
      - 'agentune_simulate/poetry.lock'
  push:
    branches:
      - main
    paths:
      - 'agentune_simulate/agentune/**'
      - 'agentune_simulate/tests/**'
      - 'agentune_simulate/pyproject.toml'
      - 'agentune_simulate/poetry.lock'

permissions:
  contents: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  python_tests:
    uses: ./.github/workflows/python-tests.yml
    with:
      src_path: "agentune_simulate"
